GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/4

###
DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Daniel",
  "number": "12345678"
}

###
PUT http://localhost:3001/api/persons/62915d17fe6e39c9dfc4ab6b
Content-Type: application/json

{
  "name": "Daniel",
  "number": "123-562323278"
}

###
GET http://secure-depths-75434.herokuapp.com/api/persons

###
GET https://secure-depths-75434.herokuapp.com/api/persons/6291326e2a56bfb331491af5

###
POST https://secure-depths-75434.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Daniel",
  "number": "123456789"
}

###
DELETE https://secure-depths-75434.herokuapp.com/api/persons/6795629

