GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/4

###
DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Daniel",
  "number": "123456789"
}

###
PUT http://localhost:3001/api/persons/62911a731752b186a1fc483f
Content-Type: application/json

{
  "name": "New name",
  "number": "123-456-789"
}

###
GET http://secure-depths-75434.herokuapp.com/api/persons

###
GET https://secure-depths-75434.herokuapp.com/api/persons/4

###
POST https://secure-depths-75434.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Daniel",
  "number": "123456789"
}

###
DELETE https://secure-depths-75434.herokuapp.com/api/persons/6795629

